---
- name: Simple AWX Test Playbook
  hosts: all
  become: true
  tasks:
    - name: Ping the target
      ansible.builtin.ping:

    - name: Create a test file
      ansible.builtin.file:
        path: /tmp/test_awx.txt
        state: touch
        mode: '0644'
